function  results = results5MethodExperiment( )
% Return a structure array with the results of the experiment for 5 methods
%
% Uses the data obtained from loadSpectra and the random number generator
% seeded with the number 59524208158 (subscriber number from a magazine
% near my elbow concatenated with the shipping number on a box across the
% room) to run the experiment
%
% The structure has fields:
%
% results.data is a numeric matrix holding the results of the experiment.
%              Each row is one set of experimental conditions, each 
%              column is a parameter in that run of the experiment.
% 
% results.schema a cell array of strings. results.schema{i} is the name of
%                the parameter stored in column i of the data.
%
% results.schema_description is a cell array of strings.
%                            results.schema_description{i} describes the
%                            parameter stored in column i in more detail
%                            than results.schema{i}
%
% results.dilution_key a cell array of strings results.dilution_key{i} is a
%                      description of the dilution range indicated by a
%                      value of i in a dilution parameter
%
% results.treatment_key a cell array of strings results.treatment_key{i} is
%                       a description of the treatment group indicated by i
%                       in the treatment group parameter.
%
% results.method_key a cell array of strings results.method_key{i} is
%                    a description of the noramlization method indicated 
%                    by i in the normalization method parameter.

results.schema = {'Number of spectra','Percent control group', ...
    'Treatment group id', ...
    'Control dilution range id', 'Treatment dilution range id', ...
    'Trial number', 'Normalization method id', ...
    'RMSE'
    };

results.schema_description = {
    ['The total number of spectra in the trial. Includes both control ' ...
    'and treatment group spectra.'], ...
    ['The percentage of the total spectra that were selected from the ' ...
    'control group. A 10 means 10% were selected.'], ...
    ['ID of the spectrum category selected as the treatment group. See '...
    'the treatment_key field for the meaning of each id.'], ...
    ['ID of the dilution range for the spectra in the control group. ' ...
    'See the dilution_key field for the meaning of each id'], ...
    ['ID of the dilution range for the spectra in the treatment group. ' ...
    'See the dilution_key field for the meaning of each id'], ...
    ['The number of the trial on which this measurement was made. A ' ...
    'trial is a particular choice of input spectra, dilutions and ' ...
    'noise.'], ...
    ['ID of the normalization method for which the measurements were ' ...
    'taken. See the method_key field for a description.'], ...
    ['The Root-mean-squared-error of a regression of actual dilution ' ...
    'against the dilution calculated by this method for the spectra ' ...
    'in this group.'] ...
    };    
    
results.dilution_key = { ...
    'No dilution',...
    ['Small dilution range: divide by a number uniformly chosen from 0.4 '...
    'to 2.6 (this range comes from Torgrip''s histogram equalization '...
    'paper.)'], ...
    ['Large dilution range: divide by a number uniformly chosen from 0.01 '...
    'to 100'] ...
    };
    
results.treatment_key = { ...
    ['First control group - this should never appear because the first ' ...
    'group of control samples should always be the control group and ' ...
    'never the treatment group.'], ...
    ['No effect treatment- identical metabolite concentration ' ...
    'distribution to the control group, but samples chosen '...
    'independently.'], ...
    ['1 metabolite upregulated 20% - phenylacetylglutamine with ' ...
    'mean and standard deviation multiplied by 1.2'], ...
    ['1 metabolite upregulated 500% - phenylacetylglutamine with ' ...
    'mean and standard deviation multiplied by 5'], ...
    ['10 metabolites upregulated 500% - phenylacetylglutamine, '...
    'lysine,  citrulline,  Galactose,  beta-D-fructose,  Betaine,  '...
    'leucine,  Isoleucine,  Trimethylamine, and TMAO ' ...
    'mean and standard deviation multiplied by 5'], ...
    ['7 metabolites upregulated 500% and 8 downregulated to 1/5th - ' ...
    'phenylacetylglutamine, '...
    'lysine,  citrulline,  Galactose,  beta-D-fructose,  Betaine,  '...
    'and leucine ' ...
    'with mean and standard deviation multiplied by 5 AND' ...
    'Isoleucine,  Trimethylamine, TMAO, NMND, Hippuric_acid, ' ...
    '2_deoxycytidine, 2_deoxyadenosine, and p-cresol_sulfate' ...
    'mean and standard deviation divided by 5'], ...
    };

results.method_key = { ...
    ['Constant sum - y values are summed and multiplied by a factor to '...
    'make their sum 1000.'], ...
    ['PQN all spectra all bins - does probabilistic quotient ' ...
    'normalization using the median of all spectra and all bins from ' ...
    'those spectra to derive the dilution factor.'], ...
    ['PQN controls all bins - does probabilistic quotient ' ...
    'normalization using the median of the control spectra and all ' ...
    'bins from those spectra to derive the dilution factor.'], ...
    ['PQN all spectra inlier bins - does probabilistic quotient ' ...
    'normalization using the median of all spectra as the reference ' ...
    'spectrum and but removing all bins that generate outlier quotients ' ...
    'from those spectra when deriving the dilution factor.'], ...
    ['Histogram normalization log bins - uses Torgrip''s histogram ' ...
    'normalization with 60 bins spaced logarithmically along the y axis - ' ...
    'this is as originally published.'], ...
    ['Histogram normalization equi-bins - uses Torgrip''s histogram ' ...
    'normalization with 60 bins spaced to contain as close to an equal ' ...
    'number of samples in the reference spectrum as possible.'] ...
    };
end

