function [eval_str,y_fit,BETA,num_maxima,baseline_options,EXITFLAG] = perform_deconvolution(x,y,BETA0,lb,ub,num_maxima,x_baseline_BETA)
% Pre: BETA0 only has peaks
baseline_options = {};
baseline_options.x_baseline_BETA = x_baseline_BETA;
baseline_options.x_all = x;

[BETA,EXITFLAG] = curve_fit(x,y,1:length(x),BETA0,lb,ub,num_maxima,baseline_options);
eval_str = sprintf('BETA = %s; baseline_options = {}; baseline_options.x_baseline_BETA = %s; baseline_options.x_all = %s; num_maxima = %d; EXITFLAG=%d;',...
	mat2str(BETA),...
	mat2str(baseline_options.x_baseline_BETA),...
	mat2str(baseline_options.x_all),...
	num_maxima,...
	EXITFLAG);
y_fit = global_model(BETA,x,num_maxima,baseline_options);

