function [] = perm_test_wrap(infile, outfile)

%read params from file
[permutations, testalpha, fold, data, features, ...
    class_labels, class_numbers] = read_file(infile);

%run perm w/ cutoff
[significant_features,stats] = perm_cutoff(class_numbers,data, ...
    permutations,testalpha,fold);

%run perm test
[P_all,P_all_idxs,perm_sorted_weights,perm_weights,correct_q2,perm_q2s] ...
    = perm_test(data,class_numbers,permutations,fold);

%run opls
[fold,accuracy,mean_class_numbers,W,b,C,R2_X,R2_Y,class_numbers0,P, ...
    means_data,T_ortho,stdev_class_numbers,data0,stdevs_data,T,U, ...
    num_opls_fact,press,q2,SE,P_ortho,Y_pred] = opls_script_strat_splot(data,class_numbers,fold);

%write params to file
write_file(fold,accuracy,mean_class_numbers,W, ...
    data,b,C,R2_X,R2_Y,class_numbers0,P,class_numbers,means_data,T_ortho,P_ortho, ...
    stdev_class_numbers,data0,stdevs_data,T,U,num_opls_fact, ...
    press,q2,testalpha,permutations,class_labels,features, ...
    perm_sorted_weights, perm_weights,perm_q2s,significant_features,SE,Y_pred, ...
    outfile);

