function spec=nssd_spectra_to_spectral_collections( output_name )
% Takes the default NSSD database in the parent directory and converts it to a single spectral collection file
%
% Usage: nssd_spectra_to_spectral_collections( output_name )
%
% Where:
%
% output_name is a string giving the filename where the resulting spectra
% will be written.
% 
% The database is hard-coded to be the database that came with MetAssimulo
% 1.2. The resulting spectral collection file will be written to the file
% named 'output_name'. It is assumed that the input spectra are all sorted
% by x.

% Access the metassimulo_spectrad function (which is defined in the parent
if ~exist('metassimulo_specread.m','file')
    path(path,'..');
end

% Set up a database of the various compounds in the NSSD
nssd_root = '../NSSD'; % Root for the NSSD

idx_nssd_dirname = 1; % Index of the compound's subdirectory in the database
idx_nssd_exp = 2; % Index of the experiment number in the database
idx_nssd_proc = 3; % Index of the processed data number in the database
idx_mean_urine_conc=6; % Index of the mean urine concentration in the database
idx_hmdb_id = 8; % Index of the HMDB ID in the database

NSSD_names = { ...
    '2_deoxyadenosine','7','1','Deoxyadenosine','Deoxyadenosine','2.9','1.19','HMDB00101'; ...
    '2_deoxycytidine','7','1','Deoxycytidine','Deoxycytidine','8.58','3.56','HMDB00014'; ...
    '2_hydroxybutyrate','13','1','2-Hydroxybutyric acid','2-Hydroxybutyric acid','32.27','16.55','HMDB00008'; ...
    '2-oxoglutarate','7','1','Oxoglutaric acid','Oxoglutaric acid','77','46','HMDB00208'; ...
    'acetate','23','1','Acetic acid','Acetic acid','200','50','HMDB00042'; ...
    'Arabitol','7','1','D-Arabitol','D-Arabitol','250.8','79.2','HMDB00568'; ...
    'beta-D-fructose','7','1','D-Fructose','D-Fructose','85','46','HMDB00660'; ...
    'Betaine','7','1','Betaine','Betaine','245.52','93.19','HMDB00043'; ...
    'cis-aconitic_acid','7','1','cis-Aconitic acid','cis-Aconitic acid','393','259','HMDB00072'; ...
    'Citric_acid','7','1','Citric acid','Citric acid','2022','1081','HMDB00094'; ...
    'citrulline','21','1','Citrulline','Citrulline','14.26','6.89','HMDB00904'; ...
    'Creatine','7','1','Creatine','Creatine','343','303','HMDB00064'; ...
    'Creatinine','7','1','Creatinine','Creatinine','13200','4100','HMDB00562'; ...
    'Dimethylamine','7','1','Dimethylamine','Dimethylamine','330','39.6','HMDB00087'; ...
    'Dimethylglycine','7','1','Dimethylglycine','Dimethylglycine','81.84','35.2','HMDB00092'; ...
    'Formate','7','1','Formic acid','Formic acid','583','301','HMDB00142'; ...
    'Galactose','13','1','D-Galactose','D-Galactose','58.08','409.2','HMDB00143'; ...
    'Glutamine','7','1','L-Glutamine','L-Glutamine','485.8','147','HMDB00641'; ...
    'Glycine','7','1','Glycine','Glycine','1029','440','HMDB00123'; ...
    'glycolic_acid','7','1','Glycolic acid','Glycolic acid','752','304','HMDB00115'; ...
    'guanidoacetic_acid','7','1','Guanidoacetic acid','Guanidoacetic acid','300','132','HMDB00128'; ...
    'Hippuric_acid','22','1','Hippuric acid','Hippuric acid','2640','1300','HMDB00714'; ...
    'Histidine','7','1','L-Histidine','L-Histidine','948','371','HMDB00177'; ...
    'Isocitrate','7','1','Isocitric acid','Isocitric acid','250','124','HMDB00193'; ...
    'Isoleucine','13','1','L-Isoleucine','Isoleucine','23.8','6.6','HMDB00172'; ...
    'Lactate','7','1','L-Lactic acid','L-Lactic acid','441','127','HMDB00190'; ...
    'L-alanine','7','1','L-Alanine','L-Alanine','290','73','HMDB00161'; ...
    'L-carnosine','7','1','Carnosine','Carnosine','46.2','35.64','HMDB00033'; ...
    'leucine','7','1','L-Leucine','Leucine','39.6','9.9','HMDB00687'; ...
    'L-Glutamic_acid','7','1','L-Glutamic acid','L-Glutamic acid','22.59','9.35','HMDB00148'; ...
    'L-serine','7','1','Serine','Serine','396','179.52','HMDB00187'; ...
    'L_Tyrosine','7','1','L-Tyrosine','L-Tyrosine','361.02','184.54','HMDB00158'; ...
    'lysine','7','1','L-Lysine','L-Lysine','422.4','356.4','HMDB00182'; ...
    'Malic_acid','13','1','L-Malic acid','L-Malic acid','34.32','34.32','HMDB00156'; ...
    'Methionine','13','1','L-Methionine','L-Methionine','30','10','HMDB00696'; ...
    'N-Acetyl-L-aspartic_acid','7','1','N-Acetyl-L-aspartic acid','N-Acetyl-L-aspartic acid','5.28','5.68','HMDB00812'; ...
    'n-butyrate','7','1','Butyric acid','Butyric acid','1.14','0.11','HMDB00039'; ...
    'N-methylnicotinic_acid','100','1','Trigonelline','Trigonelline','223','22.3','HMDB00875'; ...
    'NMND','40','1','1-Methylnicotinamide','1-Methylnicotinamide','80.5','38.8','HMDB00699'; ...
    'p-cresol_sulfate','1','1','p-Cresol sulfate','p-Cresol sulfate','300','100','HMDB11635'; ...
    'Phenylacetate','7','1','Benzeneacetic acid','Benzeneacetic acid','55','6','HMDB00209'; ...
    'phenylacetylglutamine','2','1','Alpha-N-Phenylacetyl-L-','phenylacetylglutamine','937.2','79.2','HMDB06344'; ...
    'p-Hydroxyphenylacetic acid','7','1','p-Hydroxyphenylacetic acid','p-Hydroxyphenylacetic acid','92.4','27.75','HMDB00020'; ...
    'succinic_acid','26','1','Succinic acid','Succinic acid','166.32','160.12','HMDB00254'; ...
    'Taurine','7','1','Taurine','Taurine','834.24','554.4','HMDB00251'; ...
    'Threonic_acid','7','1','Threonic acid','Threonic acid','132','46.2','HMDB00943'; ...
    'TMAO','37','1','Trimethylamine N-oxide','Trimethylamine N-oxide','982.08','1011.12','HMDB00925'; ...
    'Trimethylamine','7','1','Trimethylamine','Trimethylamine','101.6','98','HMDB00906'; ...
};

% Read the compounds
num_compounds = size(NSSD_names,1);
spec = cell(num_compounds, 1);
wait_h = waitbar(0,'Reading compounds ...');
for i=1:num_compounds
    waitbar((i-1)/num_compounds, wait_h, sprintf('Reading %s', ...
        NSSD_names{i,idx_nssd_dirname}));
    base_dir = fullfile(nssd_root, NSSD_names{i, idx_nssd_dirname});
    cs=metassimulo_specread(base_dir, NSSD_names{i, idx_nssd_exp}, ...
        NSSD_names{i, idx_nssd_proc});
    if strcmp(cs, 'empty')
        delete(wait_h);
        error('nssd_spectra_to_spectral_collections:no_spectrum',...
            'No spectrum to plot in %s', base_dir);
    end
    if size(cs,2) ~= 3
        delete(wait_h);
        error('nssd_spectra_to_spectral_collections:not_one_dim',...
            'The spectrum in %s is not a 1D spectrum.', base_dir);
    end
    spec{i, 1} = cs;
end


% Calculate all the ppms (x values) that will be needed in the combined
% spectra
waitbar(0, wait_h, 'Calculating the final x values');

% Find the interval covered by all spectra 
consensus_minimum = max(cellfun(@(x) min(x(:,1)), spec));
consensus_maximum = min(cellfun(@(x) max(x(:,1)), spec));

% Set the resample locations to 32768 values that lie strictly in that 
% region
final_x = linspace(consensus_minimum, consensus_maximum, 32768+2);
final_x = final_x(2:end-1);
assert(length(final_x) == 32768);
assert(all(final_x < consensus_maximum & final_x > consensus_minimum));

% Interpolate the spectra - adding normally distributed noise where
% extrapolation would be needed (with mean and standard deviation of the
% noise taken from the mean and std of the first 100 points of the
% spectrum)
waitbar(0, wait_h, 'Interpolating');
final_y = zeros(length(final_x), num_compounds);
for i = 1:num_compounds
    waitbar((i-1)/num_compounds, wait_h);
    cs = spec{i,1}(:,2);
    if ~issorted(spec{i,1}(:,1)) && ~issorted(spec{i,1}(end:-1:1,1))
        % The spectra have to be sorted or reverse sorted so taking 
        % the first 100 values will likely lie in a noise region
        error('nssd_spectra_to_spectral_collection:not_sorted',...
            'Spectrum %d (%s) is not sorted', i, NSSD_names{i, idx_nssd_dirname});
    end
    interpd=interp1(spec{i,1}(:,1), cs, final_x, 'pchip', NaN);
    assert(~any(isnan(interpd))); % shouldn't be any extrapolation going on
    
    final_y(:,i) = interpd;
end

% Set up the spectral collection structure
waitbar(0, wait_h, 'Writing spectrum file');
clear('spec');
spec.x = final_x;
spec.Y = final_y;

num_samples = size(spec.Y,2);

spec.input_names = {'Collection ID', 'Type', 'Description', 'Processing log', 'Base sample ID', 'Time', 'Classification', 'Sample ID', 'Subject ID', 'Sample Description', 'Weight', 'Units of weight', 'Species'};
spec.formatted_input_names = {'collection_id', 'type', 'description', 'processing_log', 'base_sample_id', 'time', 'classification', 'sample_id', 'subject_id', 'sample_description', 'weight', 'units_of_weight', 'species'};
spec.collection_id=sprintf('%d',-45572);
spec.type='SpectraCollection';
spec.description=sprintf('Converted spectra from NSSD library of standards included from MetAssimulo 1.2');
spec.processing_log='Created converted from MetAssimulo 1.2 NSSD.';
spec.num_samples=num_samples; 
spec.time=zeros(1,num_samples);
spec.classification=zeros(1,num_samples);
spec.sample_id=arrayfun(@(x) sprintf('%s', NSSD_names{i, idx_hmdb_id} ), ...
    1:num_samples,'UniformOutput',false); % HMDB_ID as sample id
spec.subject_id=1:num_samples;
spec.sample_description=arrayfun(@(x) sprintf('Spectrum of %s (%s)', ...
    NSSD_names{i, idx_nssd_dirname}, NSSD_names{i, idx_hmdb_id} ), ...
    1:num_samples,'UniformOutput',false); % Use sample description to describe what compound it is a spectrum of
spec.weight=arrayfun(@(x) sprintf('%s', NSSD_names{i, idx_mean_urine_conc} ), ...
    1:num_samples,'UniformOutput',false); % Mean urine concentration as sample weight
spec.units_of_weight=arrayfun(@(x) 'Weight is mean urine concentration',1:num_samples,'UniformOutput',false);
spec.species=arrayfun(@(x) 'No species',1:num_samples,'UniformOutput',false);
spec.base_sample_id=1:num_samples;

% Write the spectrum to a file
save_collection(output_name, spec);

delete(wait_h);