function test_suite = test_equal_frequency_histogram_boundaries%#ok<STOUT>
%matlab_xUnit tests excercising sort_metabap_by_name_then_ppm
%
% Usage:
%   runtests test_equal_frequency_histogram_boundaries
initTestSuite;

function testEx01 %#ok<DEFNU>
% Runs the first example from the documentation. This tests normal
% operation with the last bin having only one element and the second to
% last bin having more than its share.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [1,1,1,2,3,4,5,5,5,5,5,6], 4 ), ...
    [1.0000    1.5000    4.5000    5.5000    6.0000], ...
    'absolute', 0.0001);

function testEx02 %#ok<DEFNU>
% Runs the second example from the documentation. This tests the first bin
% needing to be expanded and the last bin having only one element.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [1,1,1,2,3,4,5,5,5,5,5,6], 3 ), ...
    [0    2.5000    5.5000    6.0000], ...
    'absolute', 0.0001);

function testEx03 %#ok<DEFNU>
% Runs the third example from the documentation. This example tests running
% out of elements when the last bin remains to be made.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [1,1,1,2,3,4,5,5,5,5,5,5], 3 ), ...
    [0    2.5000    5.0000    7.0000], ...
    'absolute', 0.0001);

function testEx04 %#ok<DEFNU>
% Runs the fourth example from the documentation. This example tests
% running out of elements when the last two bins remain to be made. It also
% tests working with unsorted data.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [5,1,1,2,3,4,5,5,5,5,5,1], 5 ), ...
    [ 1.0000    1.5000    4.5000    5.0000    6.3333    7.6667], ...
    'absolute', 0.0001);

function testEx05 %#ok<DEFNU>
% Runs the fifth example from the documentation. This example tests
% expanding the first bin and dealing correctly with nan's and infinities.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [-inf,1,10,20,22,24,inf,25,25,25,26,26,26,27,nan], 4 ), ...
    [ -26.5219   21.0000   25.5000   26.5000   27.0000], ...
    'absolute', 0.0001);

function testEx06 %#ok<DEFNU>
% Runs the sixth example from the documentation. This example tests
% behavior on an empty array.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [], 4 ), ...
    [  0     1     2     3     4], ...
    'absolute', 0.0001);

function testEx07 %#ok<DEFNU>
% Runs the seventh example from the documentation. This example tests
% behavior on an array that will be empty after removal of infinite 
% quantities.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [-inf,inf], 4 ), ...
    [  0     1     2     3     4], ...
    'absolute', 0.0001);

function testEx08 %#ok<DEFNU>
% Runs the eighth example from the documentation. This example tests
% expanding the last bin but not the first.
assertElementsAlmostEqual(...
    equal_frequency_histogram_boundaries( [1,2,3,10,20], 2 ), ...
    [  1.0000    6.5000   41.8553], ...
    'absolute', 0.0001);



